version: "3.8"
services:
    app:
        build:
            context: .
    nginx:
        restart: always
        image: nginx:latest
        depends_on:
            - app
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
